-- Tier 1 Supporting Evidence Query
WITH COVERAGE_DETAILS AS (
    SELECT
        ASV,
        SUM(INVENTORY_COUNT) AS TOTAL_INVENTORY,
        SUM(TOTAL_EVALUATIONS_COUNT) AS TOTAL_EVALUATIONS
        ROUND(100.0 * SUM(TOTAL_EVALUATIONS_COUNT) / SUM(INVENTORY_COUNT), 2) AS COVERAGE_PERCENTAGE
        FROM (
            SELECT *,
                ROW_NUMBER() OVER (PARTITION BY ACCOUNT_NUMBER, REGION, ASV, RESOURCE_TYPE ORDER BY BATCH_ID DESC) AS RANK
                FROM CLCN_DB.PHDP_CLOUD.OZONE_QUARTERLY_EXAMINER_REVIEW_TOTAL_COUNTS_REPORT_V01_V4 
                WHERE BATCH_ID = (SELECT MAX(BATCH_ID) FROM CLCN_DB.PHDP_CLOUD.OZONE_QUARTERLY_EXAMINER_REVIEW_TOTAL_COUNTS_REPORT_V01_V4)
                AND CLOUD_PROVIDER = 'AWS'
                AND ROLE_TYPE IN ('', 'N/A', 'MACHINE')
                AND CONTROL_ID = 'CM-6.AWS.61.v02'
                AND INVENTORY_COUNT > 0
                AND LOWER(REGION) IN ('ca-central-1', 'eu-west-1', 'eu-west-2', 'us-east-1', 'us-east-2', 'us-west-2', 'global')
        ) a
        WHERE RANK = 1
        GROUP BY ASV
)
SELECT
    ASV,
    TOTAL_INVENTORY,
    TOTAL_EVALUATIONS,
    COVERAGE_PERCENTAGE,
    CASE WHEN COVERAGE_PERCENTAGE >= 100 THEN 'GREEN' ELSE 'RED' END AS COVERAGE_STATUS
    FROM COVERAGE_DETAILS
    ORDER BY COVERAGE_PERCENTAGE ASC;