-- Tier 3 Supporting Evidence Query
SELECT
    CERT.APPLICATION_ASV AS APPLICATION_NAME,
    CERT.ID,
    CERT.CERTIFICATION_TYPE,
    TO_TIMESTAMP(CERT.CREATED_DATE) AS CREATION_DATE,
    -- Determine how far past remediation SLA the certification is
    CASE
        WHEN REMEDIATION_PAST_DUE_30_DAYS = 1 THEN '30 DAYS PAST DUE REMEDIATION'
        WHEN REMEDIATION_PAST_DUE_60_DAYS = 1 THEN '60 DAYS PAST DUE REMEDIATION'
        WHEN REMEDIATION_PAST_DUE_90_DAYS = 1 THEN '90 DAYS PAST DUE REMEDIATION'
        ELSE 'WITHIN SLA'
    END AS PAST_DUE_SLA
FROM (
    -- Subquery to calculate past due remediation flags for each certification
    SELECT CERT.*,
    -- Flag certifications past remediation deadline by 30+ days
    CASE WHEN CERT.STATUS IN (0, 1, 2, 3) AND TIMESTAMPDIFF('DAY', TO_TIMESTAMP(CERT.TARGET_REMEDIATION_DATE), CURRENT_TIMESTAMP()) >= 30 THEN 1 ELSE 0 END AS REMEDIATION_PAST_DUE_30_DAYS,
    -- Flag certifications past remediation deadline by 60+ days
    CASE WHEN CERT.STATUS IN (0, 1, 2, 3) AND TIMESTAMPDIFF('DAY', TO_TIMESTAMP(CERT.TARGET_REMEDIATION_DATE), CURRENT_TIMESTAMP()) >= 60 THEN 1 ELSE 0 END AS REMEDIATION_PAST_DUE_60_DAYS,
    -- Flag certifications past remediation deadline by 90+ days
    CASE WHEN CERT.STATUS IN (0, 1, 2, 3) AND TIMESTAMPDIFF('DAY', TO_TIMESTAMP(CERT.TARGET_REMEDIATION_DATE), CURRENT_TIMESTAMP()) >= 90 THEN 1 ELSE 0 END AS REMEDIATION_PAST_DUE_90_DAYS
    FROM EIAM_DB.PHAP_ERAM_11ACAPT.AA_MICROCERTIFICATION CERT
    WHERE CERT.CERTIFICATION_TYPE = 'Compute Groups APR'
    AND TO_TIMESTAMP(CERT.CREATED_DATE) >= DATEADD(YEAR, -1, CURRENT_DATE())  -- Only look at last year
    AND CERT.STATUS = 6  -- Only certifications in remediation status
) CERT

UNION ALL
-- Return a single "no data" row if no certifications are in remediation
SELECT
    NULL AS APPLICATION_NAME,
    NULL AS ID,
    NULL AS CERTIFICATION_TYPE,
    NULL AS CREATION_DATE,
    'NO COMPUTE APR GROUPS CURRENRLTLY IN REMEDIATION' PAST_DUE_SLA
WHERE NOT EXISTS (
    -- Check if any certifications are in remediation
    SELECT 1 FROM EIAM_DB.PHAP_ERAM_11ACAPT.AA_MICROCERTIFICATION CERT
    WHERE CERT.CERTIFICATION_TYPE = 'Compute Groups APR'
    AND TO_TIMESTAMP(CERT.CREATED_DATE) >= DATEADD(YEAR, -1, CURRENT_DATE())
    AND CERT.STATUS = 6
)

-- Sort actual certifications first, followed by "no data" row if present
ORDER BY CASE WHEN APPLICATION_NAME IS NULL THEN 2 ELSE 1 END;