-- Tier 1 (Completeness) Metric
-- Join Dataset and CMDB tables to match ASVs with HPSM names
WITH JOINED_TABLE_BTWN_SF_SN AS (
    SELECT B.HPSM_NAME, A.APPLICATION_ASV
    FROM EIAM_DB.PHOP_ETAM_IDENTITYIQ.SPT_APPLICATION_ASV A
    LEFT JOIN CMDB_DB.PHDP_CMDB.CMDB_CI_SUMMARY_BC B
    ON A.APPLICATION_ASV = B.HPSM_NAME -- Match on ASV name
    WHERE A.APPLICATION_ASV IS NOT NULL
    AND INSTALL_STATUS_DESC = 'In Production' -- Only include production applications
),
-- Calculate compliance status for each ASV
COMPLIANCE_RESULT AS (
    SELECT HPSM_NAME, APPLICATION_ASV,
    -- Mark as GREEN if HPSM name exists, RED if missing
    CASE WHEN HPSM_NAME IS NOT NULL THEN 'GREEN' ELSE 'RED' END AS IN_COMPLIANCE 
    FROM JOINED_TABLE_BTWN_SF_SN
)
SELECT 
    CURRENT_DATE() AS DATE,
    'MNTR-1104900-T1' AS MONITORING_METRIC_NUMBER,
    -- Calculate percentage of compliant ASVs (rounded to 2 decimal places)
    ROUND(COUNT(CASE WHEN IN_COMPLIANCE = 'GREEN' THEN 1 END)/COUNT(*)* 100, 2) AS MONITORING_METRIC,
    -- Overall compliance is GREEN only if 100% compliant
    CASE WHEN MONITORING_METRIC = 100 THEN 'GREEN' WHEN MONITORING_METRIC < 100 THEN 'RED' END AS COMPLIANCE_STATUS,
    -- Count of compliant ASVs
    TO_DOUBLE(ROUND(COUNT(CASE WHEN IN_COMPLIANCE = 'GREEN' THEN 1 END),2)) AS NUMERATOR,
    -- Total count of ASVs
    TO_DOUBLE(ROUND(COUNT(*),2)) AS DENOMINATOR
FROM COMPLIANCE_RESULT,